modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "KRender OBJ Model Loading"
authors = "Kneelawk"
description = "Cross-platform OBJ Model Loader."
logoFile = "assets/${mod_id}/icon.png"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "krender_model_loading"
type = "REQUIRED"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "krender_engine_api"
type = "REQUIRED"
versionRange = "*"
ordering = "NONE"
side = "BOTH"
