modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mixins]]
config = "krender_engine_api.xplat.mixins.json"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "KRender Engine API"
authors = "Kneelawk"
description = "Cross-platform Render System Abstraction."
logoFile = "assets/${mod_id}/icon.png"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "common_events"
type = "REQUIRED"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"
