modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mixins]]
config = "krender.mixins.json"

[[mods]]
modId = "krender"
version = "${version}"
displayName = "KRender"
authors = "Kneelawk"
description = "Cross-platform Minecraft rendering abstraction."
logoFile = "assets/krender/icon.png"

[[dependencies.krender]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[20.5,)"
ordering = "NONE"
side = "BOTH"
